subscription AllImagesSubscription ($time: timestamptz!) {
  images: images_aggregate (where: {
    created_at: {
      _gt: $time
    }
  }) {
    aggregate {
      count
    }
    nodes {
      id
    }
  }
}
