#import "./ImageFragment.gql"
query AllImages ($offset: Int, $limit: Int, $where: images_bool_exp){
  images: images_aggregate(offset: $offset, limit: $limit, order_by: {created_at: desc}, where: $where) {
    aggregate {
      count
    }
    nodes {
      ...Image
    }
  }
}
